/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as ScoutingAggregatesRouteImport } from './routes/scouting/aggregates'
import { Route as ScoutingEventsRouteImport } from './routes/scouting/events'
import { Route as ScoutingPlayersRouteImport } from './routes/scouting/players'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingAggregatesRoute = ScoutingAggregatesRouteImport.update({
  id: '/scouting/aggregates',
  path: '/scouting/aggregates',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingEventsRoute = ScoutingEventsRouteImport.update({
  id: '/scouting/events',
  path: '/scouting/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutingPlayersRoute = ScoutingPlayersRouteImport.update({
  id: '/scouting/players',
  path: '/scouting/players',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scouting/aggregates': typeof ScoutingAggregatesRoute
  '/scouting/events': typeof ScoutingEventsRoute
  '/scouting/players': typeof ScoutingPlayersRoute
  '/games/': typeof GamesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scouting/aggregates': typeof ScoutingAggregatesRoute
  '/scouting/events': typeof ScoutingEventsRoute
  '/scouting/players': typeof ScoutingPlayersRoute
  '/games': typeof GamesIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/directory': typeof DirectoryRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/scouting/aggregates': typeof ScoutingAggregatesRoute
  '/scouting/events': typeof ScoutingEventsRoute
  '/scouting/players': typeof ScoutingPlayersRoute
  '/games/': typeof GamesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/directory'
    | '/players/$playerId'
    | '/scouting/aggregates'
    | '/scouting/events'
    | '/scouting/players'
    | '/games/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/directory'
    | '/players/$playerId'
    | '/scouting/aggregates'
    | '/scouting/events'
    | '/scouting/players'
    | '/games'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/directory'
    | '/players/$playerId'
    | '/scouting/aggregates'
    | '/scouting/events'
    | '/scouting/players'
    | '/games/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DirectoryRoute: typeof DirectoryRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ScoutingAggregatesRoute: typeof ScoutingAggregatesRoute
  ScoutingEventsRoute: typeof ScoutingEventsRoute
  ScoutingPlayersRoute: typeof ScoutingPlayersRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/aggregates': {
      id: '/scouting/aggregates'
      path: '/scouting/aggregates'
      fullPath: '/scouting/aggregates'
      preLoaderRoute: typeof ScoutingAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/events': {
      id: '/scouting/events'
      path: '/scouting/events'
      fullPath: '/scouting/events'
      preLoaderRoute: typeof ScoutingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouting/players': {
      id: '/scouting/players'
      path: '/scouting/players'
      fullPath: '/scouting/players'
      preLoaderRoute: typeof ScoutingPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DirectoryRoute: DirectoryRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ScoutingAggregatesRoute: ScoutingAggregatesRoute,
  ScoutingEventsRoute: ScoutingEventsRoute,
  ScoutingPlayersRoute: ScoutingPlayersRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
